python:
- "3.4"
# Only build master branch
branches:
  only:
  - master
install:
# install python via brew
- which python
- python --version
# pip init
- sudo pip install --upgrade pip
# use anaconda
- sudo pip install conda
- sudo conda init
- sudo conda install --yes 'numpy<1.9.0'
# final pip installs
- sudo pip install wheel
# build extensions
- python setup.py develop
# show packages
- pip freeze
script:
# Create wheel pacakge
- python setup.py test
