python:
- "3.4"
# Only build master branch
branches:
  only:
  - master
install:
# install python via brew
- which python
- python --version
# pip init
- pip install --upgrade pip
# use anaconda
- pip install conda
- conda init
- conda install --yes 'numpy<1.9.0'
# final pip installs
- pip install wheel
# build extensions
- python setup.py develop
# show packages
- pip freeze
script:
# Create wheel pacakge
- python setup.py test
