language: python

env:
  global:
  - GH_REF: github.com/cimatosa/jobmanager.git
  - secure: Q3YVqRTs3QLspdzHgYMMuOoMypn7yetkb7v0LFe/68AwxZAwEkpCF24FHL/cEH9khc99AGbDIST81undY6kJLWLEDHYIWaoKUbC8OmaT7H6MUdfLtznsv1NnOLut9Z3So/mTMGQHCmTga9NKsuFpDMxg/oxp3wS915ar6+PLh3w=

notifications:
  email: false
  
branches:
  only:
  - master


python:
- '2.7'
- '3.4'
- '3.5'

matrix:
  allow_failures:
  - python: '2.7'
  - python: '3.5'
  
before_install:
- sudo apt-get install libhdf5-openmpi-dev
- pip install numpy
- pip install sqlitedict
- pip install h5py
- pip install pytest pytest-cov
- git clone https://github.com/cimatosa/progress.git progress_package
- ln -s progress_package/progress
- git clone https://github.com/cimatosa/binfootprint.git binfootprint_package
- ln -s binfootprint_package/binfootprint
- git clone https://github.com/cimatosa/persistentdata.git persistentdata_package
- ln -s persistentdata_package/persistentdata


script:
- py.test tests/ -v --cov=progress --cov-report term-missing

after_success:
- bash <(curl -s https://codecov.io/bash)
