# Mac OS X Python build
language:
- objective-c
python:
- "3.4"
# Only build master branch
branches:
  only:
  - master
install:
# install python via brew
- which python
- python --version
# pip init
- pip install --upgrade pip
# use anaconda
- pip install conda
- conda init
- conda install --yes 'numpy<1.9.0'
# final pip installs
- pip install wheel
# show packages
- pip freeze
# build extensions
- python setup.py develop
script:
# Create wheel pacakge
- python setup.py test
