language: python
notifications:
  email: false
python:
- "3.4"
- "2.7"
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
- wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b
- export PATH=/home/travis/miniconda/bin:$PATH
- conda update --yes conda
- travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib
install:
- travis_retry pip install sqlitedict
- travis_retry pip install psutil
- pip freeze
script:
- netstat -tulpen
- travis_wait python setup.py test

