language: python
python:
- "3.4"
# Only build master branch
branches:
  only:
  - master
before_install:
# We need to use conda, because virtualenv did not work on travis with 3.4
- sudo apt-get update -qq
- sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
- sudo wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- sudo chmod +x miniconda.sh
- sudo ./miniconda.sh -b
- export PATH=/home/travis/miniconda/bin:$PATH
- sudo conda update --yes conda
- travis_retry sudo conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy
install:
- travis_retry sudo python setup.py develop
- python --version
- pip freeze
script:
- travis_wait sudo python setup.py test
cache: apt
