language: python
notifications:
  email: false
python:
- "3.4"
virtualenv:
  system_site_packages: true
before_install:
- sudo apt-get update -qq
- if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then sudo apt-get -y install python-numpy python-scipy python-psutil; fi
- if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then sudo apt-get -y install python3-numpy python3-scipy python-psutil; fi
install:
- travis_retry pip install sqlitedict
- pip freeze
script:
- travis_wait python setup.py test

