language: python
python:
- "3.4"
# Only build master branch
branches:
  only:
  - master
before_install:
- sudo apt-get update -qq
install:
- if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then sudo apt-get install python-numpy; fi
- if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then sudo apt-get install python3-numpy; fi
- travis_retry python setup.py develop
- python --version
- pip freeze
script:
- travis_wait python setup.py test
cache: apt
